# Generated by Django 3.0.10 on 2022-04-09 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20220327_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='properties/%Y/%m/%d/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
        ),
    ]
