# Generated by Django 3.0.10 on 2022-04-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
        ),
    ]
